# Generated by Django 4.1 on 2023-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_admin_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_car', models.BooleanField(default=False, verbose_name='Is Car')),
                ('is_bike', models.BooleanField(default=False, verbose_name='Is Bike')),
            ],
        ),
    ]
