# Generated by Django 4.1 on 2023-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='dropd',
            field=models.TextField(default=None),
        ),
    ]
