# Generated by Django 4.1 on 2023-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bookingdetails_dropd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='dropd',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='Date1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='Date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='Time1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='Time2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='location',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
