# Generated by Django 4.1 on 2023-01-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bookingdetails_bookingdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='Date1',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='Date2',
            new_name='date2',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='Time1',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='Time2',
            new_name='time2',
        ),
    ]
