# Generated by Django 4.1 on 2023-01-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_bookingdetails_bookingdetails_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(null=True)),
                ('date2', models.DateField(null=True)),
                ('time1', models.TimeField(null=True)),
                ('time2', models.TimeField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
