# Generated by Django 4.1 on 2023-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_datemodel_delete_dtmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemodel',
            name='date1',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='date2',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='location',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='time1',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='time2',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
