# Generated by Django 4.1 on 2023-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_datemodel_date1_datemodel_date2_datemodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datemodel',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='time2',
        ),
        migrations.AddField(
            model_name='datemodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='datemodel',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
