# Generated by Django 4.1 on 2023-01-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_datemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datemodel',
            name='name',
        ),
    ]
