# Generated by Django 4.1 on 2023-01-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_datemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemodel',
            name='uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Uname'),
        ),
    ]
