# Generated by Django 4.1 on 2023-01-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_datemodel_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemodel',
            old_name='uname',
            new_name='user',
        ),
    ]
